name: Testing and deployment

on:
  push:
    branches: [cicd]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      POSTGRES_ENGINE: ${{ secrets.DB_ENGINE }}
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      POSTGRES_HOST: ${{ secrets.DB_HOST }}
      POSTGRES_PORT: ${{ secrets.DB_PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "1"
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}

    services:
      postgres-main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Проверка репозитория на наличие изменений
        uses: actions/checkout@v3

      - name: Подготовка Python-окружения
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Линтинг
        run: flake8 logistic/ --exclude=logistic/migrations/

      - name: Тестирование
        run: python manage.py test
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: ${{ env.DEBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ env.POSTGRES_ENGINE }}
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DB_HOST: ${{ env.POSTGRES_HOST }}
          DB_PORT: ${{ env.POSTGRES_PORT }}